monitoreo/urls.py
from django.conf.urls import url
from django.contrib import admin

from graficas.views import info_datos_server, info_datos_server_google
from graficas.views_grafana import api_grafana

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', api_grafana, name='graficas_grafana'),
    url(r'^graficas-plotly$', info_datos_server, name='graficas_plotly'),
    url(r'^graficas-google$', info_datos_server_google, name='graficas_google'),

]

graficas/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.


class Empresa(models.Model):
    slug = models.SlugField(unique=True)
    nombre = models.CharField(max_length=80, unique=True)

    def __unicode__(self):
        return u'{0}'.format(self.nombre)

class GrafanaData(models.Model):
    token_admin = models.CharField(max_length=100,  blank=True)
    token_viewer = models.CharField(max_length=100,  blank=True)  # Opcional
    id_org = models.IntegerField(null=True)
    uuid_dashboard = models.CharField(max_length=80, unique=True, null=True, blank=True)
    id_dashboard = models.IntegerField(null=True, blank=True),
    url = models.CharField(max_length=150, unique=True, blank=True, null=True)
    title = models.CharField(max_length=80, blank=True, null=True)
    version = models.IntegerField(blank=True, null=True)


class GrafanaDB(models.Model):
    uuid_db = models.UUIDField()
    db_name = models.CharField(max_length=100, default='telegraf')
    empresa = models.ForeignKey(Empresa, related_name='_dashboard', null=True)

graficas/forms/forms_graficas.py
#!
# -*- coding: utf-8 -*-
#

from django import forms

from graficas.models import Empresa


class GraficasForm(forms.Form):
    TIEMPO = (
        ('5m', 'Últimos 5 minutos'),
        ('15m', 'Ùltimos 15 minutos'),
        ('30m', 'Ùltimos 30 minutos'),
        ('1h', 'Ùltima 1 hora'),
        ('3h', 'Ùltimas 3 horas'),
        ('6h', 'Ùltimas 6 horas'),
        ('12h', 'Ùltimas 12 horas'),
        ('24h', 'Ùltimas 24 horas'),
        ('2d', 'Ùltimos 2 dias'),
        ('7d', 'Ùltimos 7 dias'),
        ('30d', 'Ùltimos 30 dias'),
    )
    RANGO = (
        ('10s', '10s'),
        ('1m', '1m'),
        ('5m', '5m'),
        ('10m', '10m'),
        ('15m', '15m'),
        ('1h', '1h'),
        ('1d', '1d'),
    )
    rango = forms.ChoiceField(choices=RANGO, label="Rango:", required=False, initial='1m')
    tiempo = forms.ChoiceField(choices=TIEMPO, label="Tiempo:", required=True, initial='15m')
    empresa = forms.ModelChoiceField(queryset=Empresa.objects.all(), label="Empresa", required=True)

class EmpresaForm(forms.Form):

    empresa = forms.ModelChoiceField(queryset=Empresa.objects.all(), label="Empresa", required=True)

graficas/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import json
from influxdb import InfluxDBClient

from django.shortcuts import render
from dateutil import parser
from plotly.offline import plot
from plotly.graph_objs import Scatter
from graficas.forms.forms_graficas import GraficasForm, EmpresaForm
from graficas.models import Empresa, GrafanaDB, GrafanaData
from graficas.views_grafana import obtener_db_grafana
from monitoreo import settings
from pytz import timezone

# Create your views here.

def info_datos_server(request):
    tiempo = ""
    empresa = Empresa.objects.first()
    form = GraficasForm(initial={'empresa': empresa})
    if request.method == 'POST':
        form = GraficasForm(request.POST)
        tiempo = form.data.get('tiempo')
        rango = form.data.get('rango')
        empresa_id = form.data.get('empresa')
        empresa = Empresa.objects.get(id=empresa_id)
        grafana_data =GrafanaData.objects.all()
        grafana_data = grafana_data [0]
        grafana_db = GrafanaDB.objects.filter(empresa=empresa)
        if not grafana_db:
            grafana_db = obtener_db_grafana(empresa, grafana_data)
        else:
            grafana_db = grafana_db[0]
        if rango is None:
            if tiempo in ['1h', '3h']:
                rango = '10m'
            elif tiempo in ['6h', '12h', '24h']:
                rango = '1h'
            elif tiempo in ['2d', '7d', '30d']:
                rango = '1d'
            else:
                rango = '1m'
            form = GraficasForm(initial={'tiempo': tiempo, 'rango': rango})
        client = InfluxDBClient(settings.IP_INFLUXDB, 8086, 'root', 'root', grafana_db.db_name)
        result = client.query('SELECT mean("used") FROM "mem" WHERE time >= now() - '+ tiempo +' GROUP BY time('+ rango +') fill(null)')
        result_cpu = client.query(
            'SELECT mean("usage_system") FROM "cpu" WHERE time >= now() - '+ tiempo +' GROUP BY time('+ rango +') fill(null)')

        result_net_speed = client.query(
            'SELECT non_negative_derivative(mean("bytes_recv"), 1s) *8 as "download bytes/sec",  '
            'non_negative_derivative(mean("bytes_sent"), 1s) *8 as '
            '"upload bytes/sec" FROM net WHERE time > now() - '+ tiempo +' GROUP BY time(15s)')
        result_net_used = client.query('SELECT non_negative_difference(mean("bytes_recv")) *2 FROM "net" '
                                       'WHERE time >= now() -' + tiempo + ' GROUP BY time(15s) fill(null)')
    else:
        grafana_data = GrafanaData.objects.all()
        grafana_data = grafana_data[0]
        grafana_db = GrafanaDB.objects.filter(empresa=empresa)
        if not grafana_db:
            grafana_db = obtener_db_grafana(empresa, grafana_data)
        else:
            grafana_db = grafana_db[0]
        client = InfluxDBClient(settings.IP_INFLUXDB, 8086, 'root', 'root', grafana_db.db_name)
        result = client.query(
            'SELECT mean("used") FROM "mem" WHERE time >= now() - 15m GROUP BY time(1m) fill(null)')
        result_cpu = client.query(
            'SELECT mean("usage_system") FROM "cpu" WHERE time >= now() - 15m GROUP BY time(1m) fill(null)')
        result_net_speed = client.query(
            'SELECT non_negative_derivative(mean("bytes_recv"), 1s) *8 as "download bytes/sec", non_negative_derivative(mean("bytes_sent"), 1s) *8 as '
            '"upload bytes/sec" FROM net WHERE time > now() - 15m GROUP BY time(15s)')
        result_net_used = client.query('SELECT non_negative_difference(mean("bytes_recv")) *2 FROM "net" '
                                       'WHERE time >= now() - 15m GROUP BY time(15s) fill(null)')

    x_data = []
    y_data = []
    for response in result:
        for registro in response:
            if registro['mean']:
                memoria_usada = float(registro['mean'])
            else:
                memoria_usada = None
            hora = parser.parse(registro['time'])
            hora_final = hora.astimezone(timezone('America/Cancun')).strftime("%H:%M:%S")
            if tiempo in ['24h', '2d', '7d', '30d']:
                hora_final = hora.astimezone(timezone('America/Cancun')).strftime("%d/%m -%H:%M:%S")
            x_data.append(hora_final)
            y_data.append(memoria_usada)
    x_data_cpu = []
    y_data_cpu = []

    for response_cpu in result_cpu:
        for registro_cpu in response_cpu:
            if registro_cpu['mean']:
                memoria_usada = float(registro_cpu['mean'])
            else:
                memoria_usada = None
            hora = parser.parse(registro_cpu['time'])
            hora_final = hora.astimezone(timezone('America/Cancun')).strftime("%H:%M:%S")
            if tiempo in ['24h', '2d', '7d', '30d']:
                hora_final = hora.astimezone(timezone('America/Cancun')).strftime("%d/%m -%H:%M:%S")
            x_data_cpu.append(hora_final)
            y_data_cpu.append(memoria_usada)

    x_data_net = []
    download_y_data_net = []
    upload_y_data_net = []

    for response_net in result_net_speed:
        for registro_net in response_net:
            if registro_net['download bytes/sec']:
                download_bytes = float(registro_net['download bytes/sec'])
                if download_bytes < 0:
                    download_bytes = 0.0
            else:
                download_bytes = None
            if registro_net['upload bytes/sec']:
                upload_bytes = float(registro_net['upload bytes/sec'])
                if upload_bytes < 0:
                    upload_bytes = 0.0
            else:
                upload_bytes = None
            hora = parser.parse(registro_net['time'])
            hora_final = hora.astimezone(timezone('America/Cancun')).strftime("%H:%M:%S")
            if tiempo in ['24h', '2d', '7d', '30d']:
                hora_final = hora.astimezone(timezone('America/Cancun')).strftime("%d/%m -%H:%M:%S")
            x_data_net.append(hora_final)
            download_y_data_net.append(download_bytes)
            upload_y_data_net.append(upload_bytes)

    x_data_net_used = []
    y_data_net_used = []
    for response_net_used in result_net_used:
        for registro_net_used in response_net_used:
            if registro_net_used['non_negative_difference']:
                memoria_usada = float(registro_net_used['non_negative_difference'])
            else:
                memoria_usada = None
            hora = parser.parse(registro_net_used['time'])
            hora_final = hora.astimezone(timezone('America/Cancun')).strftime("%H:%M:%S")
            if tiempo in ['24h', '2d', '7d', '30d']:
                hora_final = hora.astimezone(timezone('America/Cancun')).strftime("%d/%m -%H:%M:%S")
            x_data_net_used.append(hora_final)
            y_data_net_used.append(memoria_usada)

    plot_div = plot([Scatter(x=x_data, y=y_data,
                             mode='lines', name='test',
                             opacity=0.8, marker_color='green')],
                    output_type='div')

    plot_div_cpu = plot([Scatter(x=x_data_cpu, y=y_data_cpu,
                             mode='lines', name='test',
                             opacity=0.8, marker_color='red')],
                    output_type='div')

    plot_div_net = plot([Scatter(x=x_data_net, y=download_y_data_net,
                                 mode='lines', name='Download bytes/sec',
                                 opacity=0.9, marker_color='blue'), Scatter(x=x_data_net, y=upload_y_data_net,
                                 mode='lines', name='Upload bytes/sec',
                                 opacity=0.9, marker_color='red')],
                        output_type='div')

    plot_div_net_used = plot([Scatter(x=x_data_net_used, y=y_data_net_used,
                                 mode='lines', name='Bytes',
                                 opacity=0.8, marker_color='blue')],
                        output_type='div')

    return render(request, 'dashboard.html', {'plot_div': plot_div, 'form': form, 'plot_div_cpu': plot_div_cpu,
                                              'plot_div_net': plot_div_net, 'plot_div_net_used': plot_div_net_used})

def info_datos_server_google(request):
    tiempo = ""
    empresa = Empresa.objects.first()
    form = GraficasForm(initial={'empresa': empresa})

    if request.method == 'POST':
        form = GraficasForm(request.POST)
        tiempo = form.data.get('tiempo')
        rango = form.data.get('rango')
        empresa_id = form.data.get('empresa')
        empresa = Empresa.objects.get(id=empresa_id)
        grafana_data = GrafanaData.objects.all()
        grafana_data = grafana_data[0]
        grafana_db = GrafanaDB.objects.filter(empresa=empresa)
        if not grafana_db:
            grafana_db = obtener_db_grafana(empresa, grafana_data)
        else:
            grafana_db = grafana_db[0]
        if rango is None:
            if tiempo in ['1h', '3h']:
                rango = '10m'
            elif tiempo in ['6h', '12h', '24h']:
                rango = '1h'
            elif tiempo in ['2d', '7d', '30d']:
                rango = '1d'
            else:
                rango = '1m'
            form = GraficasForm(initial={'tiempo': tiempo, 'rango': rango})
        client = InfluxDBClient(settings.IP_INFLUXDB, 8086, 'root', 'root', grafana_db.db_name)
        result = client.query(
            'SELECT mean("used") FROM "mem" WHERE time >= now() - ' + tiempo + ' GROUP BY time(' + rango + ') fill(null)')
        result_cpu = client.query(
            'SELECT mean("usage_system") FROM "cpu" WHERE time >= now() - ' + tiempo + ' GROUP BY time(' + rango + ') fill(null)')

        result_net_speed = client.query(
            'SELECT non_negative_derivative(mean("bytes_recv"), 1s) *8 as "download bytes/sec",  '
            'non_negative_derivative(mean("bytes_sent"), 1s) *8 as '
            '"upload bytes/sec" FROM net WHERE time > now() - ' + tiempo + ' GROUP BY time(15s)')

graficas/templates/api_grafana.html
{% extends "base.html" %}
{% load i18n widget_tweaks %}
{% block body %}
    <div class="m-4">
        <form class="form-inline my-3 my-lg-0" id="form-empresa" method="post">{% csrf_token %}
         <label class="control-label control-label-required m-2">{{ form_empresa.empresa.label }}</label>
            {% render_field form_empresa.empresa class="form-control col-1" data-rule-required="true" %} {{ form_empresa.empresa.errors }}
           <a class="btn btn-primary m-4" href="admin/graficas/empresa/add/" target="_blank" role="button">Crear Empresa</a>
        </form>
    </div>
    <iframe width=100% src="{{ url }}" height=100% border="0" frameborder="0"></iframe>

{% endblock %}
{% block scripts %}
    <script type="text/javascript">
    jQuery(document).ready(function() {
       $("#id_empresa").change(function () {
           if($("#id_empresa").val()){
               $("#form-empresa").submit()
           }
       });
      });
    </script>
{% endblock %}

graficas/templates/base.html
{% load i18n widget_tweaks %}
<html>
  <head>
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
      {% block extra_head_files %} {% endblock %}
  </head>
  <body>
  <nav class="navbar navbar-expand-lg sticky-top navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Graficas</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Graficas
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'graficas_grafana'%}">Graficas Grafana</a>
            <a class="dropdown-item" href="{% url 'graficas_plotly'%}">Graficas Plotly</a>
            <a class="dropdown-item" href="{% url 'graficas_google'%}">Graficas Google</a>
        </div>
      </li>
    </ul>
    <form class="form-inline my-3 my-lg-0" id="form-tiempo" method="post">{% csrf_token %}
     <label style="color: white">{{ form.tiempo.label }}</label>
            {% render_field form.tiempo class="form-control col-3" data-rule-required="true" %} {{ form.tiempo.errors }}

        <label style="color: white">{{ form.rango.label }}</label>
            {% render_field form.rango class="form-control col-3" data-rule-required="true" %} {{ form.tiempo.errors }}
        <label style="color: white">{{ form.empresa.label }}</label>
        {% render_field form.empresa class="form-control col-2" data-rule-required="true" %} {{ form.empresa.errors }}

    </form>
  </div>
</nav>
{% block body %}
  {% endblock %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.min.js"></script>
  {% block scripts %}
  {% endblock %}
</html>

graficas/templates/dashboard.html
{% extends "base.html" %}
{% block body %}
        <div class="row">
    <div class="col-6" style="height: 20%">
        <h3 style="text-align: center">Memoria</h3>
        {% autoescape off %}
            {{ plot_div }}
        {% endautoescape %}

    </div>
    <div class="col-6" style="height: 20%">
        <h3 style="text-align: center">Bytes/Sec</h3>

        {% autoescape off %}
            {{ plot_div_net }}
        {% endautoescape %}

    </div>

    </div>
    <br>
    <br>
    <div class="row">
        <div  class="col-6" style="height: 20%">
        <h3 style="text-align: center">CPU</h3>
            {% autoescape off %}
                {{ plot_div_cpu }}
            {% endautoescape %}
    </div>
    <div  class="col-6" style="height: 20%">
        <h3 style="text-align: center">Bytes Download</h3>
            {% autoescape off %}
                {{  plot_div_net_used }}
            {% endautoescape %}
    </div>
    </div>
{% endblock %}
{%  block scripts %}
       <script type="text/javascript">
        jQuery(document).ready(function() {
            $("#id_tiempo").change(function(){
                $("#id_rango").val("")
                 if($("#id_empresa").val()){
                     $("#form-tiempo").submit()
                 }


            });
            $("#id_rango").change(function(){
                if($("#id_empresa").val()){
                    $("#form-tiempo").submit()
                }

            });
             $("#id_empresa").change(function(){
                  if($("#id_empresa").val()){
                      $("#form-tiempo").submit()
                  }

            });


        });
    </script>
{% endblock %}

graficas/templates/dashboard_google.html
{% extends "base.html" %}
{% block extra_head_files %}
          <!-- Graficas Memoria -->
      <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
      google.charts.load('current', {'packages':['corechart']});
      google.charts.setOnLoadCallback(drawChart);

      function drawChart() {
        var data = google.visualization.arrayToDataTable({{ data_mem|safe }});

        var options = {
          title: 'Memoria',
          hAxis: {title: 'Tiempo',  titleTextStyle: {color: '#333'}},
          vAxis: {
          viewWindowMode:'explicit',
              viewWindow:{
                min:{{ mem_min }},
              }}
        };

        var chart = new google.visualization.AreaChart(document.getElementById('chart_div'));
        chart.draw(data, options);
      }
    </script>
      <!-- Graficas Net -->
      <script type="text/javascript">
      google.charts.load('current', {'packages':['corechart']});
      google.charts.setOnLoadCallback(drawChart);

      function drawChart() {
        var data = google.visualization.arrayToDataTable({{ data_net|safe }});

        var options = {
          title: 'Bytes/Sec',
          hAxis: {title: 'Tiempo',  titleTextStyle: {color: '#333'}},
          vAxis: {
          viewWindowMode:'explicit',
              viewWindow:{
                min:{{ net_min }},
              }}
        };

        var chart = new google.visualization.AreaChart(document.getElementById('chart_div_net'));
        chart.draw(data, options);
      }
    </script>
      <!-- Graficas CPU -->
      <script type="text/javascript">
      google.charts.load('current', {'packages':['corechart']});
      google.charts.setOnLoadCallback(drawChart);

      function drawChart() {
        var data = google.visualization.arrayToDataTable({{ data_cpu|safe }});

        var options = {
          title: 'CPU',
          hAxis: {title: 'Tiempo',  titleTextStyle: {color: '#333'}},
          vAxis: {
          viewWindowMode:'explicit',
              viewWindow:{
                min:{{ cpu_min }},
              }}
        };

        var chart = new google.visualization.AreaChart(document.getElementById('chart_div_cpu'));
        chart.draw(data, options);
      }
    </script>
     <!-- Net Used -->
      <script type="text/javascript">
      google.charts.load('current', {'packages':['corechart']});
      google.charts.setOnLoadCallback(drawChart);

      function drawChart() {
        var data = google.visualization.arrayToDataTable({{ data_net_used|safe }});

        var options = {
          title: 'Kb Download',
          hAxis: {title: 'Tiempo',  titleTextStyle: {color: '#333'}},
          vAxis: {
          viewWindowMode:'explicit',
              viewWindow:{
                min:{{ net_min_used }},
              }}
        };

        var chart = new google.visualization.AreaChart(document.getElementById('chart_div_net_used'));
        chart.draw(data, options);
      }
    </script>
{% endblock %}
{% block body %}
        <div class="row" style="height: 50%">
    <div class="col-6"  >
        <div id="chart_div" style="width: 100%; height: 100%;"></div>
    </div>
    <div class="col-6">
        <div id="chart_div_net" style="width: 100%; height: 100%;"></div>
    </div>

    </div>
    <br>
    <br>
    <div class="row" style="height: 50%">
       <div class="col-6">
            <div id="chart_div_cpu" style="width: 100%; height: 100%;"></div>
        </div>
        <div class="col-6">
            <div id="chart_div_net_used" style="width: 100%; height: 100%;"></div>
        </div>
    </div>
{% endblock %}
{%  block scripts %}
       <script type="text/javascript">
        jQuery(document).ready(function() {
            $("#id_tiempo").change(function(){
                $("#id_rango").val("")
                 if($("#id_empresa").val()){
                     $("#form-tiempo").submit()
                 }


            });
            $("#id_rango").change(function(){
                if($("#id_empresa").val()){
                    $("#form-tiempo").submit()
                }

            });
             $("#id_empresa").change(function(){
                  if($("#id_empresa").val()){
                      $("#form-tiempo").submit()
                  }

            });


        });
    </script>
{% endblock %}